runtime: go121

env_variables:
  GIN_MODE: release
  GOOGLE_REDIRECT_URL: "https://goreadapp.com/auth/callback"
  GOOGLE_CLOUD_PROJECT: "goread-467200"
  SECRET_CLIENT_ID_NAME: "google-client-id"
  SECRET_CLIENT_SECRET_NAME: "google-client-secret"

beta_settings:
  cloud_sql_instances: []

handlers:
- url: /static
  static_dir: web/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
