runtime: go122

env_variables:
  GIN_MODE: release
  GOOGLE_REDIRECT_URL: "https://goreadapp.com/auth/callback"
  GOOGLE_CLOUD_PROJECT: "goread-467200"
  SECRET_CLIENT_ID_NAME: "google-client-id"
  SECRET_CLIENT_SECRET_NAME: "google-client-secret"
  CSRF_SECRET: ${CSRF_SECRET}
  SUBSCRIPTION_ENABLED: "true"
  ADMIN_TOKEN: ${ADMIN_TOKEN}
  INITIAL_ADMIN_EMAILS: ${INITIAL_ADMIN_EMAILS}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
  
beta_settings:
  cloud_sql_instances: []

handlers:
- url: /static
  static_dir: web/static
  secure: always

- url: /.*
  script: auto
  secure: always

instance_class: F2  # 512MB RAM - matches previous Flex config

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65  # Scale up when CPU > 65% (vs default ~50%)
