runtime: go121

env_variables:
  GIN_MODE: release
  GOOGLE_CLIENT_ID: "1022472352583-e0hkm6ejmdi6mc04079fkvharhrcda8k.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REDIRECT_URL: "https://goreadapp.com/auth/callback"

handlers:
- url: /static
  static_dir: web/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
