runtime: go121
app_engine_apis: true

env_variables:
  GIN_MODE: release
  GOOGLE_CLIENT_ID: _secret:google-client-id
  GOOGLE_CLIENT_SECRET: _secret:google-client-secret
  GOOGLE_REDIRECT_URL: "https://goreadapp.com/auth/callback"

handlers:
- url: /static
  static_dir: web/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
