const globals = {
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  fetch: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  CustomEvent: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  Notification: 'readonly',
  IntersectionObserver: 'readonly',
  MutationObserver: 'readonly',
  matchMedia: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  DOMPurify: 'readonly',
  marked: 'readonly',
  CSSStyleDeclaration: 'readonly',
  module: 'readonly',
};

module.exports = [
  {
    files: ['web/static/js/**/*.js'],
    ignores: ['web/static/js/**/*.min.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals,
    },
    rules: {
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': 'off',
    },
  },
];
