name: Docs

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.md'
      - '.markdown-link-check.json'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.markdown-link-check.json'
      - 'package.json'
      - 'package-lock.json'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Check documentation links and anchors
      run: make docs
